[features]
seeds = false
skip-lint = false

[programs.devnet]
flash_loan = "ARsgcuCrXQSQDrAsuyKNkbgGcS76ni4Rak6uEfibmELH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
