const protocols = [
  {
    id: 1,
    name: "Cashio",
    title: "Stablecoin",
    amount: "$48,000,000.00",
    exploit_type: "Faulty Account Validation ",
    technique: "Fake Collateral validated correctly",
    audit_by: "Unaudited",
    hackmd_link: "https://security.superteam.fun/hacks/cahio-hack",
    link: "/hacks/cashio-hack",
    doh: "2022-03-23",
  },
  {
    id: 2,
    name: "Jet",
    title: "Lending and Borrowing Crypto Assets",
    amount: "$0.00",
    exploit_type: "Vulnerability ",
    technique:
      "Broken C-ratio calculation leading to borrow all liquidity without posting collateral ",
    audit_by: "Ottersec",
    hackmd_link: "https://security.superteam.fun/hacks/jet-hack",
    link: "/hacks/jet-hack",
    doh: "2021-12-21",
  },
  {
    id: 3,
    name: "Wormhole",
    title: "Bridge",
    amount: "$325,000,000.00",
    exploit_type: "Spoofed Signature exploit",
    technique:
      "Bypass validation of fake signatures to authorisee mint of 120k ETH",
    audit_by: "Neodyme",
    hackmd_link: "https://security.superteam.fun/hacks/wormhole-hack",
    link: "/hacks/wormhole-hack",
    doh: "2022-02-02",
  },
  {
    id: 4,
    name: "Crema",
    title: "Concentrated Liquidity Provider ",
    amount: "$8,800,000.00",
    exploit_type: "Faulty Account Validation ",
    technique: "Fake Account supplied to issue excess LP fees",
    audit_by: "Bramah Systems",
    hackmd_link: "https://security.superteam.fun/hacks/crema-hack",
    link: "/hacks/crema-hack",
    doh: "2022-07-03",
  },
  {
    id: 5,
    name: "Nirvana",
    title: "Stablecoin",
    amount: "$3,500,000.00",
    exploit_type: "Flashloan Attack",
    technique: "Inflate price using flashloan to drain protocol treasury",
    audit_by: "Sec3 Auto Audit Software",
    hackmd_link: "https://security.superteam.fun/hacks/nirvana",
    link: "/hacks/nirvana",
    doh: "2022-07-28",
  },
  {
    id: 6,
    name: "Raydium",
    title: "Order book Decentralized Exchange",
    amount: "$4,400,000.00",
    exploit_type: "Private Key Compromised",
    technique:
      "Illegally withdraw liquidity by using compromised admin's private key.",
    audit_by: "N/A",
    hackmd_link: "https://security.superteam.fun/hacks/raydium-hack",
    link: "/hacks/raydium-hack",
    doh: "2022-12-16",
  },
  {
    id: 7,
    name: "Mango ",
    title: "Leverage Trading",
    amount: "$115,000,000.00",
    exploit_type: "Price Manipulation",
    technique:
      "Manipulate $MNGO price to profit from leveraged open long position. Use unrealized PNL to borrow liquidity.",
    audit_by: "N/A",
    hackmd_link: "https://hackmd.io/q3J-B87pRV2R0k7mlBl2Jw?view",
    link: "/hacks/mango-hack",
    doh: "2022-10-11",
  },
  {
    id: 8,
    name: "Solend",
    title: "Lending and Borrowing Crypto Assets",
    amount: "$1,260,000.00",
    exploit_type: "Price Oracle Attack",
    technique: "Inflated price of collateral to borrow excess liquidity",
    audit_by: "N/A",
    hackmd_link: "https://hackmd.io/@prastut/Bkxx_JC-h",
    link: "/hacks/solend-poa-hack",
    doh: "2022-11-02",
  },
  {
    id: 9,
    name: "Solend",
    title: "Lending and Borrowing Crypto Assets",
    amount: "$0.00",
    exploit_type: "Faulty Account Validation ",
    technique:
      "Bypass admin checks using fake account to manipulate core protocol parameters",
    audit_by: "N/A",
    hackmd_link: "https://hackmd.io/@prastut/r1wMdtcf3",
    link: "/hacks/solend-fav-hack",
    doh: "2021-08-19",
  },
  {
    id: 10,
    name: "Slope wallet",
    title: "Wallet",
    amount: "$5,000,000.00",
    exploit_type: "Private Key Compromise",
    technique:
      "Transferred assets to hacker account using compromised private key",
    audit_by: "N/A",
    hackmd_link: "https://hackmd.io/@prastut/SJoJUzKz3",
    link: "/hacks/slope-wallet-hack",
    doh: "2022-08-02",
  },
];

export default protocols;
